<link rel="stylesheet" type="text/css" href="css/style.css" />
<link rel="stylesheet" type="text/css" href="css/nivo-slider.css" />
<link rel="stylesheet" type="text/css" href="css/nivo-slider-default.css" />
<link type="text/css" href="css/jquery-ui.css" rel="stylesheet" />
<link rel="stylesheet" href="css/chrome.css" type="text/chrome/safari" />
<link href="css/lightbox.css" rel="stylesheet" />
<script src="js/jquery-1.11.0.min.js"></script>
<script src="js/jquery.nivo.slider.js"></script>
<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script type="text/JavaScript" src="js/my_jquery.js"></script>
<script type="text/javascript" src="korpa.js"></script>
